### ISSUE TITLE
problem with matplotlib with Mac OS X virtualenv

### ISSUE THREAD

**Issue by mhsieh** [PacificBiosciences/pitchfork#170]
```
$ bash --init-file deployment/setup-env.sh 
bash-3.2$ python
Python 2.7.10 (default, Jul 14 2015, 19:46:27) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib.pyplot
/Users/mhsieh/pitchfork/deployment/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mhsieh/pitchfork/deployment/lib/python2.7/site-packages/matplotlib/pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/Users/mhsieh/pitchfork/deployment/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/Users/mhsieh/pitchfork/deployment/lib/python2.7/site-packages/matplotlib/backends/backend_macosx.py", line 24, in <module>
    from matplotlib.backends import _macosx
RuntimeError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are Working with Matplotlib in a virtual enviroment see 'Working with Matplotlib in Virtual environments' in the Matplotlib FAQ
>>> ^D
bash-3.2$ /usr/bin/python
Python 2.7.10 (default, Jul 14 2015, 19:46:27) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib.pyplot as plt
```

**Comment by mhsieh** [comment]
http://matplotlib.org/faq/virtualenv_faq.html#osx

**Comment by pb-cdunn** [comment]
Same issue here:
* http://wiki.wxpython.org/wxPythonVirtualenvOnMac

I'd punt. What needs matplotlib?

**Comment by mhsieh** [comment]
Forgot to reply, sorry. Matplotlib is required by pbreports.
Best,
--mj
From a unix device.
On Feb 24, 2016, at 15:21, Christopher Dunn <notifications@github.com<mailto:notifications@github.com>> wrote:

Same issue here:

  *   http://wiki.wxpython.org/wxPythonVirtualenvOnMac

I'd punt. What needs matplotlib?

**Comment by pb-cdunn** [comment]
I see. Might be a little painful, but a good idea would be to alter pbreports to send descriptions to a stand-alone executable, which can generate the pics. It's much easier to install an executable than a library. matplotlib is probably not a good thing to use anymore.

**Comment by mhsieh** [comment]
I am not in a hurry, since nobody yet to request to run resequencing on the Mac. (/me winks at @mpkocher)

**Comment by mpkocher** [comment]
+1 for Core Reseq on OSX

matplotlib works fine on OSX in a virtualenv for me.

**Comment by pb-cdunn** [comment]
mpkocher, interesting datapoint, but google it. Many troubles.

**Comment by mhsieh** [comment]
```
$ pbsmrtpipe pipeline-id pbsmrtpipe.pipelines.sa3_ds_resequencing -e eid_subread:$HOME/tmp/Analysis_Results/m150404_101626_42267_c100807920800000001823174110291514_s1_p0.all.subreadset.xml -e eid_ref_dataset:$HOME/tmp/lambdaNEB/lambdaNEB.referenceset.xml --output-dir $HOME/tmp/ --local-only
Registry Loaded. Number of ToolContracts:117 FileTypes:55 ChunkOperators:13 Pipelines:43
successfully initialized datastore.
completed setting up job directory resources and logs in /Users/mhsieh/tmp
successfully created job resources.
starting to execute Distributed workflow with assigned job_id 681808
system Darwin mjs-macbook-pro.nanofluidics.com nproc:8
exe'ing workflow Cluster renderer None
Service URI: None <type 'NoneType'> (fqdn = mjs-macbook-pro.nanofluidics.com)
Max number of Chunks  128 
Max number of nproc   8
Max number of workers 100
tmp dir               /tmp
Unable to find any chunkable tasks from 0 chunk operators.
validating binding graph
successfully validated binding graph.
Starting worker pbalign.tasks.pbalign-0 (1 workers running, 8 total proc in use)
Task was successful TaskResult(task_id='pbalign.tasks.pbalign-0', state='successful', error_message='', run_time_sec=46.53)
Successfully validated outputs of <TaskBindingNode pbalign.tasks.pbalign-0>
Workflow status 3/8 completed/total tasks
Starting worker pbalign.tasks.consolidate_alignments-0 (1 workers running, 1 total proc in use)
Task was successful TaskResult(task_id='pbalign.tasks.consolidate_alignments-0', state='successful', error_message='', run_time_sec=1.01)
Successfully validated outputs of <TaskBindingNode pbalign.tasks.consolidate_alignments-0>
Workflow status 4/8 completed/total tasks
Starting worker genomic_consensus.tasks.variantcaller-0 (1 workers running, 8 total proc in use)
Task was successful TaskResult(task_id='genomic_consensus.tasks.variantcaller-0', state='successful', error_message='', run_time_sec=52.83)
Successfully validated outputs of <TaskBindingNode genomic_consensus.tasks.variantcaller-0>
Workflow status 5/8 completed/total tasks
Starting worker genomic_consensus.tasks.gff2vcf-0 (1 workers running, 1 total proc in use)
Starting worker pbreports.tasks.mapping_stats-0 (2 workers running, 2 total proc in use)
Starting worker genomic_consensus.tasks.gff2bed-0 (3 workers running, 3 total proc in use)
Task was successful TaskResult(task_id='genomic_consensus.tasks.gff2vcf-0', state='successful', error_message='', run_time_sec=1.01)
Successfully validated outputs of <TaskBindingNode genomic_consensus.tasks.gff2vcf-0>
Workflow status 6/8 completed/total tasks
Task pbreports.tasks.mapping_stats-0 Failed task pbreports.tasks.mapping_stats exit code 1 in 1.01 sec (See file '/Users/mhsieh/tmp/tasks/pbreports.tasks.mapping_stats-0/stderr'.)
Extracted from stderr
Running task in /Users/mhsieh/tmp/tasks/pbreports.tasks.mapping_stats-0
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/mhsieh/pitchfork/deployment/lib/python2.7/site-packages/pbreports/report/mapping_stats.py", line 25, in <module>
    from pbreports.plot.rainbow import make_rainbow_plot
  File "/Users/mhsieh/pitchfork/deployment/lib/python2.7/site-packages/pbreports/plot/rainbow.py", line 15, in <module>
    import matplotlib.pyplot as plt
  File "/Users/mhsieh/pitchfork/deployment/lib/python2.7/site-packages/matplotlib/pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/Users/mhsieh/pitchfork/deployment/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/Users/mhsieh/pitchfork/deployment/lib/python2.7/site-packages/matplotlib/backends/backend_macosx.py", line 24, in <module>
    from matplotlib.backends import _macosx
RuntimeError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are Working with Matplotlib in a virtual enviroment see 'Working with Matplotlib in Virtual environments' in the Matplotlib FAQ


Workflow status 6/8 completed/total tasks
Shutting down.
Completed execution pbsmrtpipe v0.36.6. Workflow Failed in 105.16 sec (1.75 min)
```

**Comment by mhsieh** [comment]
```
$ make reseq-core
$ bash --init-file deployment/setup-env.sh 
bash-3.2$ pbsmrtpipe pipeline-id pbsmrtpipe.pipelines.sa3_ds_resequencing -e eid_subread:$HOME/tmp/Analysis_Results/m150404_101626_42267_c100807920800000001823174110291514_s1_p0.all.subreadset.xml -e eid_ref_dataset:$HOME/tmp/lambdaNEB/lambdaNEB.referenceset.xml --output-dir $HOME/tmp/ --local-only
Registry Loaded. Number of ToolContracts:117 FileTypes:55 ChunkOperators:13 Pipelines:43
successfully initialized datastore.
completed setting up job directory resources and logs in /Users/mhsieh/tmp
successfully created job resources.
starting to execute Distributed workflow with assigned job_id 388056
system Darwin mjs-macbook-pro.nanofluidics.com nproc:8
exe'ing workflow Cluster renderer None
Service URI: None <type 'NoneType'> (fqdn = mjs-macbook-pro.nanofluidics.com)
Max number of Chunks  128 
Max number of nproc   8
Max number of workers 100
tmp dir               /tmp
Unable to find any chunkable tasks from 0 chunk operators.
validating binding graph
successfully validated binding graph.
Starting worker pbalign.tasks.pbalign-0 (1 workers running, 8 total proc in use)
Task was successful TaskResult(task_id='pbalign.tasks.pbalign-0', state='successful', error_message='', run_time_sec=46.53)
Successfully validated outputs of <TaskBindingNode pbalign.tasks.pbalign-0>
Workflow status 3/8 completed/total tasks
Starting worker pbalign.tasks.consolidate_alignments-0 (1 workers running, 1 total proc in use)
Task was successful TaskResult(task_id='pbalign.tasks.consolidate_alignments-0', state='successful', error_message='', run_time_sec=1.01)
Successfully validated outputs of <TaskBindingNode pbalign.tasks.consolidate_alignments-0>
Workflow status 4/8 completed/total tasks
Starting worker genomic_consensus.tasks.variantcaller-0 (1 workers running, 8 total proc in use)
Task was successful TaskResult(task_id='genomic_consensus.tasks.variantcaller-0', state='successful', error_message='', run_time_sec=52.84)
Successfully validated outputs of <TaskBindingNode genomic_consensus.tasks.variantcaller-0>
Workflow status 5/8 completed/total tasks
Starting worker genomic_consensus.tasks.gff2vcf-0 (1 workers running, 1 total proc in use)
Starting worker pbreports.tasks.mapping_stats-0 (2 workers running, 2 total proc in use)
Starting worker genomic_consensus.tasks.gff2bed-0 (3 workers running, 3 total proc in use)
Task was successful TaskResult(task_id='genomic_consensus.tasks.gff2vcf-0', state='successful', error_message='', run_time_sec=1.01)
Successfully validated outputs of <TaskBindingNode genomic_consensus.tasks.gff2vcf-0>
Workflow status 6/8 completed/total tasks
Task was successful TaskResult(task_id='genomic_consensus.tasks.gff2bed-0', state='successful', error_message='', run_time_sec=1.01)
Successfully validated outputs of <TaskBindingNode genomic_consensus.tasks.gff2bed-0>
Workflow status 7/8 completed/total tasks
Task was successful TaskResult(task_id='pbreports.tasks.mapping_stats-0', state='successful', error_message='', run_time_sec=21.02)
Successfully validated outputs of <TaskBindingNode pbreports.tasks.mapping_stats-0>
Workflow status 8/8 completed/total tasks
Shutting down.
Completed execution pbsmrtpipe v0.36.6. Workflow was Successful in 126.19 sec (2.10 min)
```
