### ISSUE TITLE
blank lines in settings.mk

### ISSUE THREAD

**Issue by pb-cdunn** [PacificBiosciences/pitchfork#246]
```sh
$ make cython
...
make[1]: Entering directory `/lustre/hpcprod/cdunn/repo/gh/pitchfork/ports/python/cython'
/lustre/hpcprod/cdunn/repo/gh/pitchfork/bin/pitchfork fetch --url https://pypi.python.org/packages/source/C/Cython/Cython-0.24.tar.gz
{'url': 'https://pypi.python.org/packages/source/C/Cython/Cython-0.24.tar.gz', 'subcommand': 'fetch'}
```
```py
Traceback (most recent call last):
  File "/lustre/hpcprod/cdunn/repo/gh/pitchfork/bin/pitchfork", line 276, in <module>
    sys.exit(main())
  File "/lustre/hpcprod/cdunn/repo/gh/pitchfork/bin/pitchfork", line 269, in main
    pitchfork(pargs)
  File "/lustre/hpcprod/cdunn/repo/gh/pitchfork/bin/pitchfork", line 156, in pitchfork
    if '#' in line.lstrip()[0]:
IndexError: string index out of range
```

**Comment by pb-cdunn** [comment]
I'll fix this.
