### ISSUE TITLE
ConsensusCore2 depends on pbcopper

### ISSUE THREAD

**Issue by pb-cdunn** [PacificBiosciences/pitchfork#310]
This is not urgent. I'm just recording what occurred.

My latest pbsmrtpipe run failed after updating git repos, so I did

```
git pull origin master # to update pitchfork
make _startover
make pbreports # slow but successful
make pbfalcon
```

I got this failure:

```
    [100%] Building CXX object swig/CMakeFiles/_ConsensusCore2.dir/ConsensusCore2_wrap.cxx.o
    cd /tmp/pip-5BdbRc-build/build/temp.linux-x86_64-2.7/swig && ccache /home/UNIXHOME/cdunn/pf/bin/g++   -D_ConsensusCore2_EXPORTS -fPIC -I/home/UNIXHOME
/cdunn/pf/include  -std=c++11 -Wall -Wextra -Wno-unused-parameter -Wno-unused-variable -Wno-unused-local-typedefs -O2 -g -DNDEBUG -fPIC -isystem /home/UNI
XHOME/cdunn/pf/include -isystem /opt/python-2.7.9/include/python2.7 -isystem /home/UNIXHOME/cdunn/pf/lib/python2.7/site-packages/numpy/core/include -I/tmp
/pip-5BdbRc-build/include -I/tmp/pip-5BdbRc-build/build/temp.linux-x86_64-2.7/generated -I/tmp/pip-5BdbRc-build/third-party/pbcopper/include    -fPIC -o C
MakeFiles/_ConsensusCore2.dir/ConsensusCore2_wrap.cxx.o -c /tmp/pip-5BdbRc-build/build/temp.linux-x86_64-2.7/swig/ConsensusCore2_wrap.cxx
    make[5]: *** No rule to make target `../../third-party/pbcopper/lib/libpbcopper.a', needed by `swig/lib/_ConsensusCore2.so'.  Stop.
...
InstallationError: Command "/home/UNIXHOME/cdunn/pf/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-5BdbRc-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-60nhQK-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/UNIXHOME/cdunn/pf/include/site/python2.7/ConsensusCore2" failed with error code 1 in /tmp
make[1]: Leaving directory `/home/UNIXHOME/cdunn/repo/gh/pitchfork/ports/pacbio/unanimity'
make: *** [unanimity] Error 2
```

I then did this:

```
make pbcopper
make pbfalcon
```

So we need a pbcopper dependency in the pitchfork Makefile. (This was all single-cpu, not `make -j`.)

**Comment by mjhsieh** [comment]
This seems to be a problem of unanimity build, it should look for the one in the installation. Let me figure out what has changed in unanimity.

**Comment by mjhsieh** [comment]
please try again after travis ci dot turns green.

**Comment by armintoepfer** [comment]
CC2 now depends on pbcopper. Somehow, we always forget pitchfork in our workflow... @nlhepler might be able to help if MJ didn't already figure it out

**Comment by pb-cdunn** [comment]
I forgot to post another crash yesterday. More recently I have this:
```
$ python -m falcon_polish.mains.run_variantCaller --log-level DEBUG --options '--algorithm arrow --minConfidence 40 --minCoverage 5 --alignmentSetRefWindows'         /home/UNIXHOME/cdunn/repo/pb/smrtanalysis-client/smrtanalysis/siv/testkit-jobs/sa3_pipelines/hgap5_fake/synth5k/job_output/tasks/falcon_ns.tasks.task_hgap_run-0/run-gc_scatter/chunk_alignmentset_1.alignmentset.xml         /home/UNIXHOME/cdunn/repo/pb/smrtanalysis-client/smrtanalysis/siv/testkit-jobs/sa3_pipelines/hgap5_fake/synth5k/job_output/tasks/falcon_ns.tasks.task_hgap_run-0/run-fasta2referenceset/asm.referenceset.xml         consensus.fastq         variants.gff         consensus.fasta         consensus.contigset.xml

$ run-gc-01:master$ variantCaller --log-level DEBUG --algorithm arrow --minConfidence 40 --minCoverage 5 --alignmentSetRefWindows --referenceFilename /home/UNIXHOME/cdunn/repo/pb/smrtanalysis-client/smrtanalysis/siv/testkit-jobs/sa3_pipelines/hgap5_fake/synth5k/job_output/tasks/falcon_ns.tasks.task_hgap_run-0/run-fasta2referenceset/asm.referenceset.xml -o consensus.fastq -o variants.gff -o consensus.fasta /home/UNIXHOME/cdunn/repo/pb/smrtanalysis-client/smrtanalysis/siv/testkit-jobs/sa3_pipelines/hgap5_fake/synth5k/job_output/tasks/falcon_ns.tasks.task_hgap_run-0/run-gc_scatter/chunk_alignmentset_1.alignmentset.xml

Traceback (most recent call last):
  File "/home/UNIXHOME/cdunn/repo/pb/pf/smrtanalysis/bioinformatics/ext/pi/pbcommand/pbcommand/cli/core.py", line 136, in _pacbio_main_runner
    return_code = exe_main_func(*args, **kwargs)
  File "/home/UNIXHOME/cdunn/repo/pb/pf/smrtanalysis/bioinformatics/ext-vc/pivc/GenomicConsensus/GenomicConsensus/main.py", line 381, in args_runner
    return tr.main()
  File "/home/UNIXHOME/cdunn/repo/pb/pf/smrtanalysis/bioinformatics/ext-vc/pivc/GenomicConsensus/GenomicConsensus/main.py", line 308, in main
    self._algorithm = self._algorithmByName(options.algorithm, peekFile)
  File "/home/UNIXHOME/cdunn/repo/pb/pf/smrtanalysis/bioinformatics/ext-vc/pivc/GenomicConsensus/GenomicConsensus/main.py", line 89, in _algorithmByName
    from GenomicConsensus.arrow import arrow
  File "/home/UNIXHOME/cdunn/repo/pb/pf/smrtanalysis/bioinformatics/ext-vc/pivc/GenomicConsensus/GenomicConsensus/arrow/__init__.py", line 33, in <module>
    import utils
  File "/home/UNIXHOME/cdunn/repo/pb/pf/smrtanalysis/bioinformatics/ext-vc/pivc/GenomicConsensus/GenomicConsensus/arrow/utils.py", line 41, in <module>
    import ConsensusCore2 as cc
ImportError: No module named ConsensusCore2
```
But I'll try rebuilding unanimity first.

**Comment by pb-cdunn** [comment]
My last comment might not be a pitchfork problem. I had to use symlinks for variantCaller. I don't remember why now, but I think someone suggested that as a way to get around some problem.

```
$ ls -l /home/UNIXHOME/cdunn/repo/pb/pf/bin/variantCaller
lrwxrwxrwx 1 cdunn Domain Users 141 Sep  2 15:44 /home/UNIXHOME/cdunn/repo/pb/pf/bin/variantCaller -> /pbi/dept/secondary/builds/mainline/current_smrttools_incremental_installdir/private/pacbio/pythonpkgs/GenomicConsensus/binwrap/variantCaller
```
But that should work. The binwrap is *designed* to ignore the rest of the shell environment. So why does it fail to find `CC2`? And isn't that symlink completely up-to-date?
```
$ ls -l /pbi/dept/secondary/builds/mainline/current_smrttools_incremental_installdir/private/pacbio/pythonpkgs/GenomicConsensus/binwrap/variantCaller
-r-xr-xr-x 1 build Domain Users 711 Oct 18 15:25 /pbi/dept/secondary/builds/mainline/current_smrttools_incremental_installdir/private/pacbio/pythonpkgs/GenomicConsensus/binwrap/variantCaller
```
Maybe I need to get that via **unanimity** now? But if so, why is it still in the build? Is `current_smrttools_incremental_installdir` no longer a valid symlink?

**Comment by pb-cdunn** [comment]
Nvm. Today `CC2` is found when I run `variantCaller`. So the dependency is the only issue.
