### ISSUE TITLE
fetch not working 

### ISSUE THREAD

**Issue by MichelMoser** [PacificBiosciences/pitchfork#388]
Hello, 

I try to install blasr on a cluster node using pitchfork. 

It seems that all the thirdparty software which should get downloaded by the make-script fails to get fetched. 
When i check the directories, the supposed fetched files are not there. 
If i copy the tar.gz files myself into the directories, the installation works and just stops when trying to fetch the next third-party software. 

Is there an easy solution? Probably just an issue with the python code. 

i am using python 2.7.2

Thanks, 
Michel

Error: 
```
make[1]: Leaving directory `/home/mmoser/pitchfork/ports/thirdparty/boost'
make -C ports/thirdparty/hdf5 do-install
make[1]: Entering directory `/home/mmoser/pitchfork/ports/thirdparty/hdf5'
/home/mmoser/pitchfork/bin/pitchfork fetch --url https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.16/src/hdf5-1.8.16.tar.gz
fetching https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.16/src/hdf5-1.8.16.tar.gz
{'url': 'https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.16/src/hdf5-1.8.16.tar.gz', 'subcommand': 'fetch'}
Traceback (most recent call last):
  File "/home/mmoser/pitchfork/bin/pitchfork", line 327, in <module>
    sys.exit(main())
  File "/home/mmoser/pitchfork/bin/pitchfork", line 320, in main
    pitchfork(pargs)
  File "/home/mmoser/pitchfork/bin/pitchfork", line 307, in pitchfork
    _out, _exit, _err = backticks('grep %s MD5SUM | md5sum -c -' % os.path.basename(_prefetch), checked=True)
  File "/home/mmoser/pitchfork/bin/pitchfork", line 55, in backticks
    errCode, cmd, errorMessage))
Exception: 1 <- `grep hdf5-1.8.16.tar.gz MD5SUM | md5sum -c -`
        md5sum: hdf5-1.8.16.tar.gz: No such file or directory
hdf5-1.8.16.tar.gz: FAILED open or read
md5sum: WARNING: 1 of 1 listed file could not be read
make[1]: *** [hdf5-1.8.16.tar.gz] Error 1
make[1]: Leaving directory `/home/mmoser/pitchfork/ports/thirdparty/hdf5'
make: *** [hdf5] Error 2

```

**Comment by mhsieh** [comment]
Which Linux distro and version are you using? I think you curl command is not doing its job on for https URLs.

**Comment by MichelMoser** [comment]
your right, it was an issue with curl. 
Solved it, thank you!

**Comment by mhsieh** [comment]
Specifying alternative to curl for pitchfork is indeed on my todo list. I will add an issue for that.
