### ISSUE TITLE
I am trying to run Quiver I get this error

### ISSUE THREAD

**Issue by WIAIW** [PacificBiosciences/pitchfork#394]
Hi,

I have a BAM file, created using Blasr. I wanted to run Quiver on my file, but got an error message. 
My reference is a fasta file.
It got the following error:

'pb'
Traceback (most recent call last):
  File "/mnt/scratch/xdemo002/Downloads/pitchfork/deployment/lib/python2.7/site-packages/pbcommand/cli/core.py", line 137, in _pacbio_main_runner
    return_code = exe_main_func(*args, **kwargs)
  File "/mnt/scratch/xdemo002/Downloads/pitchfork/deployment/lib/python2.7/site-packages/GenomicConsensus/main.py", line 381, in args_runner
    return tr.main()
  File "/mnt/scratch/xdemo002/Downloads/pitchfork/deployment/lib/python2.7/site-packages/GenomicConsensus/main.py", line 297, in main
    with AlignmentSet(options.inputFilename) as peekFile:
  File "/mnt/scratch/xdemo002/Downloads/pitchfork/deployment/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 2672, in __init__
    super(AlignmentSet, self).__init__(*files, **kwargs)
  File "/mnt/scratch/xdemo002/Downloads/pitchfork/deployment/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 1959, in __init__
    super(ReadSet, self).__init__(*files, **kwargs)
  File "/mnt/scratch/xdemo002/Downloads/pitchfork/deployment/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 479, in __init__
    self.updateCounts()
  File "/mnt/scratch/xdemo002/Downloads/pitchfork/deployment/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 2513, in updateCounts
    self.assertIndexed()
  File "/mnt/scratch/xdemo002/Downloads/pitchfork/deployment/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 2343, in assertIndexed
    self._assertIndexed((IndexedBamReader, CmpH5Reader))
  File "/mnt/scratch/xdemo002/Downloads/pitchfork/deployment/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 1916, in _assertIndexed
    self._openFiles()
  File "/mnt/scratch/xdemo002/Downloads/pitchfork/deployment/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 2040, in _openFiles
    resource = IndexedBamReader(location)
  File "/mnt/scratch/xdemo002/Downloads/pitchfork/deployment/lib/python2.7/site-packages/pbcore/io/align/BamIO.py", line 388, in __init__
    super(IndexedBamReader, self).__init__(fname, referenceFastaFname)
  File "/mnt/scratch/xdemo002/Downloads/pitchfork/deployment/lib/python2.7/site-packages/pbcore/io/align/BamIO.py", line 199, in __init__
    self._checkFileCompatibility()
  File "/mnt/scratch/xdemo002/Downloads/pitchfork/deployment/lib/python2.7/site-packages/pbcore/io/align/BamIO.py", line 188, in _checkFileCompatibility
    checkedVersion = self.version
  File "/mnt/scratch/xdemo002/Downloads/pitchfork/deployment/lib/python2.7/site-packages/pbcore/io/align/BamIO.py", line 274, in version
    return self.peer.header["HD"]["pb"]
KeyError: 'pb'
[ERROR] 'pb'
Traceback (most recent call last):
  File "/mnt/scratch/xdemo002/Downloads/pitchfork/deployment/lib/python2.7/site-packages/pbcommand/cli/core.py", line 137, in _pacbio_main_runner
    return_code = exe_main_func(*args, **kwargs)
  File "/mnt/scratch/xdemo002/Downloads/pitchfork/deployment/lib/python2.7/site-packages/GenomicConsensus/main.py", line 381, in args_runner
    return tr.main()
  File "/mnt/scratch/xdemo002/Downloads/pitchfork/deployment/lib/python2.7/site-packages/GenomicConsensus/main.py", line 297, in main
    with AlignmentSet(options.inputFilename) as peekFile:
  File "/mnt/scratch/xdemo002/Downloads/pitchfork/deployment/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 2672, in __init__
    super(AlignmentSet, self).__init__(*files, **kwargs)
  File "/mnt/scratch/xdemo002/Downloads/pitchfork/deployment/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 1959, in __init__
    super(ReadSet, self).__init__(*files, **kwargs)
  File "/mnt/scratch/xdemo002/Downloads/pitchfork/deployment/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 479, in __init__
    self.updateCounts()
  File "/mnt/scratch/xdemo002/Downloads/pitchfork/deployment/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 2513, in updateCounts
    self.assertIndexed()
  File "/mnt/scratch/xdemo002/Downloads/pitchfork/deployment/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 2343, in assertIndexed
    self._assertIndexed((IndexedBamReader, CmpH5Reader))
  File "/mnt/scratch/xdemo002/Downloads/pitchfork/deployment/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 1916, in _assertIndexed
    self._openFiles()
  File "/mnt/scratch/xdemo002/Downloads/pitchfork/deployment/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 2040, in _openFiles
    resource = IndexedBamReader(location)
  File "/mnt/scratch/xdemo002/Downloads/pitchfork/deployment/lib/python2.7/site-packages/pbcore/io/align/BamIO.py", line 388, in __init__
    super(IndexedBamReader, self).__init__(fname, referenceFastaFname)
  File "/mnt/scratch/xdemo002/Downloads/pitchfork/deployment/lib/python2.7/site-packages/pbcore/io/align/BamIO.py", line 199, in __init__
    self._checkFileCompatibility()
  File "/mnt/scratch/xdemo002/Downloads/pitchfork/deployment/lib/python2.7/site-packages/pbcore/io/align/BamIO.py", line 188, in _checkFileCompatibility
    checkedVersion = self.version
  File "/mnt/scratch/xdemo002/Downloads/pitchfork/deployment/lib/python2.7/site-packages/pbcore/io/align/BamIO.py", line 274, in version
    return self.peer.header["HD"]["pb"]
KeyError: 'pb'

this is the first time that I use this software. It seems that could be an header bam problem. 
How I can fix it?

**Comment by MichelMoser** [comment]
same problem here!
Created the bam file for quiver with blasr directly from old C2-P4 data using the bax.h5-files: 

```
blasr --nproc 8 file${corr_num}.fofn /data1/projects/p023/P.AXILLARIS/P.axillaris.chromosomes.fasta --out ${corr_num}_axillaris.bam --bam
```

then merged them with picardtools and indexed them : 

```
java -jar /home/mmoser/picard2.9.0.jar MergeSamFiles I=10_axillaris.bam.bam I=11_axillaris.bam.bam I=12_axillaris.bam.bam I=13_axillaris.bam.bam I=14_axillaris.bam.bam I=15_axillaris.bam.bam I=16_axillaris.bam.bam I=17_axillaris.bam.bam I=18_axillaris.bam.bam I=19_axillaris.bam.bam I=1_axillaris.bam.bam I=20_axillaris.bam.bam I=21_axillaris.bam.bam I=22_axillaris.bam.bam I=23_axillaris.bam.bam I=24_axillaris.bam.bam I=25_axillaris.bam.bam I=26_axillaris.bam.bam I=27_axillaris.bam.bam I=28_axillaris.bam.bam I=29_axillaris.bam.bam I=2_axillaris.bam.bam I=30_axillaris.bam.bam I=31_axillaris.bam.bam I=32_axillaris.bam.bam I=33_axillaris.bam.bam I=34_axillaris.bam.bam I=35_axillaris.bam.bam I=36_axillaris.bam.bam I=37_axillaris.bam.bam I=38_axillaris.bam.bam I=39_axillaris.bam.bam I=3_axillaris.bam.bam I=40_axillaris.bam.bam I=41_axillaris.bam.bam I=42_axillaris.bam.bam I=43_axillaris.bam.bam I=44_axillaris.bam.bam I=45_axillaris.bam.bam I=46_axillaris.bam.bam I=47_axillaris.bam.bam I=48_axillaris.bam.bam I=49_axillaris.bam.bam I=4_axillaris.bam.bam I=50_axillaris.bam.bam I=51_axillaris.bam.bam I=52_axillaris.bam.bam I=53_axillaris.bam.bam I=54_axillaris.bam.bam I=55_axillaris.bam.bam I=56_axillaris.bam.bam I=57_axillaris.bam.bam I=58_axillaris.bam.bam I=59_axillaris.bam.bam I=5_axillaris.bam.bam I=60_axillaris.bam.bam I=61_axillaris.bam.bam I=62_axillaris.bam.bam I=6_axillaris.bam.bam I=7_axillaris.bam.bam I=8_axillaris.bam.bam I=9_axillaris.bam.bam O=axC2P4.axCHr.bam VALIDATION_STRINGENCY=SILENT MAX_RECORDS_IN_RAM=50000 TMP_DIR=/data6/users/moser USE_THREADING=true

pbindex axC2P4.axCHr.bam

```

**Comment by MichelMoser** [comment]
looked like in my case the first header-line was missing the pb:3.0.1 as i reheadered the bamfiles for merging with picardtools. 

blasr's bam-header comes with SO:UNKNOWN which is not accepted by picardtools, so you have to change it to "unsorted" before merging the files. 
 
Afterwards reheader the merged bamfile again to what it should look like for quiver input: 
@HD     VN:1.5  SO:coordinate   pb:3.0.1
