### ISSUE TITLE
Unable to install ConsensusCore2 python library

### ISSUE THREAD

**Issue by gabyrech** [PacificBiosciences/pitchfork#396]
Dear all,
I've been trying for a while to install the ConsensusCore2 python library following the instructions in: 
https://github.com/PacificBiosciences/unanimity/blob/master/doc/INSTALL.md
I meet all requirements (system-wide installed boost (>=1.58.0), cmake (3.2), python 2.x, and a c++11 compiler (>=gcc-5.3.0, clang), and my system is  Debian 3.16.36-1+deb8u2.
The error I get is the last step:
`pip install --upgrade --no-deps .`

```[42/61] Building CXX object src/CMakeFiles/cc2.dir/Evaluator.cpp.o
    FAILED: /usr/bin/c++   -I../../include -Igenerated -I/usr/local/include -I../../third-party/pbcopper/include -std=c++11 -Wall -Wextra -Wno-unused-parameter -Wno-unused-variable -Wno-unused-local-typedefs -O2 -g -DNDEBUG   -fPIC -MD -MT src/CMakeFiles/cc2.dir/align/AffineAlignment.cpp.o -MF src/CMakeFiles/cc2.dir/align/AffineAlignment.cpp.o.d -o src/CMakeFiles/cc2.dir/align/AffineAlignment.cpp.o -c ../../src/align/AffineAlignment.cpp
    In file included from /usr/local/include/boost/numeric/ublas/vector.hpp:21:0,
                     from /usr/local/include/boost/numeric/ublas/matrix.hpp:18,
                     from ../../src/align/AffineAlignment.cpp:44:
```
Could someone help me?
Thanks in advance!

**Comment by mhsieh** [comment]
Hi Gaby,
    Can you provide some more lines before and after the pasted printout? Thanks!
Best,
--mj

**Comment by gabyrech** [comment]
Hi @mhsieh ! Thanks for your reply.. Here you go all the lines... 
Also the versions of some of the packages needed:

```
~/soft/unanimity$ /sbin/ldconfig -v | grep 'boost'
	libboost_atomic.so.1.64.0 -> libboost_atomic.so.1.64.0
```

```
gabriel@bari:~/soft/unanimity$ gcc --version
gcc (GCC) 6.4.0
```

```
gabriel@bari:~/soft/unanimity$ c++ --version
c++ (GCC) 6.4.0

```

```
gabriel@bari:~/soft/unanimity$ cmake --version
cmake version 3.4.1
```

```
~/soft/unanimity$ sudo pip install --upgrade --no-deps .
Installing collected packages: ConsensusCore2
  Running setup.py install for ConsensusCore2 ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-ov_qGE-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-4a2S6s-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    copying swig/ConsensusCore2.py -> build/lib.linux-x86_64-2.7
    running build_ext
    Configuring with command `cmake -GNinja -DUNY_build_bin=0 -DPYTHON_SWIG=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DPYTHON_EXECUTABLE=/usr/bin/python -DUNY_build_tests=0 /tmp/pip-ov_qGE-build`
    -- The CXX compiler identification is GNU 6.4.0
    -- The C compiler identification is GNU 6.4.0
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Boost version: 1.64.0
    -- Performing Test HAS_NO_UNUSED_LOCAL_TYPEDEFS
    -- Performing Test HAS_NO_UNUSED_LOCAL_TYPEDEFS - Success
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /tmp/pip-ov_qGE-build/build/temp.linux-x86_64-2.7
    Building with command `/usr/bin/ninja _ConsensusCore2`
    [1/61] Building CXX object external/pbcopper/build/src/CMakeFiles/pbcopper.dir/cli/CLI.cpp.o
    [2/61] Building CXX object external/pbcopper/build/src/CMakeFiles/pbcopper.dir/cli/HelpPrinter.cpp.o
    [3/61] Building CXX object external/pbcopper/build/src/CMakeFiles/pbcopper.dir/cli/Interface.cpp.o
    [4/61] Building CXX object external/pbcopper/build/src/CMakeFiles/pbcopper.dir/cli/Option.cpp.o
    [5/61] Building CXX object external/pbcopper/build/src/CMakeFiles/pbcopper.dir/cli/Parser.cpp.o
    [6/61] Building CXX object external/pbcopper/build/src/CMakeFiles/pbcopper.dir/cli/Results.cpp.o
    [7/61] Building CXX object external/pbcopper/build/src/CMakeFiles/pbcopper.dir/cli/toolcontract/ResolvedToolContract.cpp.o
    [8/61] Building CXX object external/pbcopper/build/src/CMakeFiles/pbcopper.dir/cli/VersionPrinter.cpp.o
    [9/61] Building CXX object external/pbcopper/build/src/CMakeFiles/pbcopper.dir/data/Cigar.cpp.o
    [10/61] Building CXX object external/pbcopper/build/src/CMakeFiles/pbcopper.dir/cli/toolcontract/JsonPrinter.cpp.o
    [11/61] Building CXX object external/pbcopper/build/src/CMakeFiles/pbcopper.dir/data/CigarOperation.cpp.o
    [12/61] Building CXX object external/pbcopper/build/src/CMakeFiles/pbcopper.dir/data/MovieName.cpp.o
    [13/61] Building CXX object external/pbcopper/build/src/CMakeFiles/pbcopper.dir/data/RSMovieName.cpp.o
    [14/61] Building CXX object external/pbcopper/build/src/CMakeFiles/pbcopper.dir/logging/Logging.cpp.o
    [15/61] Building CXX object external/pbcopper/build/src/CMakeFiles/pbcopper.dir/utility/CallbackTimer.cpp.o
    [16/61] Building CXX object src/CMakeFiles/cc2.dir/align/AffineAlignment.cpp.o
    [17/61] Building CXX object src/CMakeFiles/cc2.dir/align/AlignConfig.cpp.o
    [18/61] Building CXX object src/CMakeFiles/cc2.dir/align/BandedChainAlignment.cpp.o
    [19/61] Building CXX object src/CMakeFiles/cc2.dir/align/LinearAlignment.cpp.o
    [20/61] Building CXX object src/CMakeFiles/cc2.dir/align/PairwiseAlignment.cpp.o
    [21/61] Building CXX object src/CMakeFiles/cc2.dir/matrix/BasicDenseMatrix.cpp.o
    [22/61] Building CXX object src/CMakeFiles/cc2.dir/matrix/ScaledMatrix.cpp.o
    [23/61] Building CXX object src/CMakeFiles/cc2.dir/matrix/SparseMatrix.cpp.o
    [24/61] Building CXX object src/CMakeFiles/cc2.dir/models/MarginalModelForm.cpp.o
    [25/61] Building CXX object src/CMakeFiles/cc2.dir/models/P6C4NoCovModel.cpp.o
    [26/61] Building CXX object src/CMakeFiles/cc2.dir/models/PwSnrAModelForm.cpp.o
    [27/61] Building CXX object src/CMakeFiles/cc2.dir/models/PwSnrModelForm.cpp.o
    [28/61] Building CXX object src/CMakeFiles/cc2.dir/models/S_P1C1Beta_Model.cpp.o
    [29/61] Building CXX object src/CMakeFiles/cc2.dir/models/S_P1C1v1_Model.cpp.o
    [30/61] Building CXX object src/CMakeFiles/cc2.dir/models/S_P1C1v2_Model.cpp.o
    [31/61] Building CXX object src/CMakeFiles/cc2.dir/models/S_P2C2v5_Model.cpp.o
    [32/61] Building CXX object src/CMakeFiles/cc2.dir/models/SnrModelForm.cpp.o
    [33/61] Building CXX object src/CMakeFiles/cc2.dir/poa/PoaAlignmentMatrix.cpp.o
    [34/61] Building CXX object src/CMakeFiles/cc2.dir/poa/PoaConsensus.cpp.o
    [35/61] Building CXX object src/CMakeFiles/cc2.dir/poa/PoaGraph.cpp.o
    [36/61] Building CXX object src/CMakeFiles/cc2.dir/poa/PoaGraphImpl.cpp.o
    [37/61] Building CXX object src/CMakeFiles/cc2.dir/poa/PoaGraphTraversals.cpp.o
    [38/61] Building CXX object src/CMakeFiles/cc2.dir/poa/RangeFinder.cpp.o
    [39/61] Building CXX object src/CMakeFiles/cc2.dir/AbstractIntegrator.cpp.o
    [40/61] Building CXX object src/CMakeFiles/cc2.dir/Coverage.cpp.o
    [41/61] Building CXX object src/CMakeFiles/cc2.dir/EasyReadScorer.cpp.o
    [42/61] Building CXX object src/CMakeFiles/cc2.dir/Evaluator.cpp.o
    FAILED: /usr/bin/c++   -I../../include -Igenerated -I/usr/local/include -I../../third-party/pbcopper/include -std=c++11 -Wall -Wextra -Wno-unused-parameter -Wno-unused-variable -Wno-unused-local-typedefs -O2 -g -DNDEBUG   -fPIC -MD -MT src/CMakeFiles/cc2.dir/align/AffineAlignment.cpp.o -MF src/CMakeFiles/cc2.dir/align/AffineAlignment.cpp.o.d -o src/CMakeFiles/cc2.dir/align/AffineAlignment.cpp.o -c ../../src/align/AffineAlignment.cpp
    In file included from /usr/local/include/boost/numeric/ublas/vector.hpp:21:0,
                     from /usr/local/include/boost/numeric/ublas/matrix.hpp:18,
                     from ../../src/align/AffineAlignment.cpp:44:
    /usr/local/include/boost/numeric/ublas/storage.hpp: In member function ‘void boost::numeric::ublas::unbounded_array<T, ALLOC>::serialize(Archive&, unsigned int)’:
    /usr/local/include/boost/numeric/ublas/storage.hpp:299:18: error: ‘make_array’ is not a member of ‘boost::serialization’
                 ar & serialization::make_array(data_, s);
                      ^~~~~~~~~~~~~
    /usr/local/include/boost/numeric/ublas/storage.hpp: In member function ‘void boost::numeric::ublas::bounded_array<T, N, ALLOC>::serialize(Archive&, unsigned int)’:
    /usr/local/include/boost/numeric/ublas/storage.hpp:494:18: error: ‘make_array’ is not a member of ‘boost::serialization’
                 ar & serialization::make_array(data_, s);
                      ^~~~~~~~~~~~~
    In file included from ../../src/align/AffineAlignment.cpp:44:0:
    /usr/local/include/boost/numeric/ublas/matrix.hpp: In member function ‘void boost::numeric::ublas::c_matrix<T, M, N>::serialize(Archive&, unsigned int)’:
    /usr/local/include/boost/numeric/ublas/matrix.hpp:5977:18: error: ‘make_array’ is not a member of ‘boost::serialization’
                 ar & serialization::make_array(data_, N);
                      ^~~~~~~~~~~~~
    FAILED: /usr/bin/c++   -I../../include -Igenerated -I/usr/local/include -I../../third-party/pbcopper/include -std=c++11 -Wall -Wextra -Wno-unused-parameter -Wno-unused-variable -Wno-unused-local-typedefs -O2 -g -DNDEBUG   -fPIC -MD -MT src/CMakeFiles/cc2.dir/align/LinearAlignment.cpp.o -MF src/CMakeFiles/cc2.dir/align/LinearAlignment.cpp.o.d -o src/CMakeFiles/cc2.dir/align/LinearAlignment.cpp.o -c ../../src/align/LinearAlignment.cpp
    In file included from /usr/local/include/boost/numeric/ublas/vector.hpp:21:0,
                     from /usr/local/include/boost/numeric/ublas/matrix.hpp:18,
                     from ../../src/align/LinearAlignment.cpp:57:
    /usr/local/include/boost/numeric/ublas/storage.hpp: In member function ‘void boost::numeric::ublas::unbounded_array<T, ALLOC>::serialize(Archive&, unsigned int)’:
    /usr/local/include/boost/numeric/ublas/storage.hpp:299:18: error: ‘make_array’ is not a member of ‘boost::serialization’
                 ar & serialization::make_array(data_, s);
                      ^~~~~~~~~~~~~
    /usr/local/include/boost/numeric/ublas/storage.hpp: In member function ‘void boost::numeric::ublas::bounded_array<T, N, ALLOC>::serialize(Archive&, unsigned int)’:
    /usr/local/include/boost/numeric/ublas/storage.hpp:494:18: error: ‘make_array’ is not a member of ‘boost::serialization’
                 ar & serialization::make_array(data_, s);
                      ^~~~~~~~~~~~~
    In file included from ../../src/align/LinearAlignment.cpp:57:0:
    /usr/local/include/boost/numeric/ublas/matrix.hpp: In member function ‘void boost::numeric::ublas::c_matrix<T, M, N>::serialize(Archive&, unsigned int)’:
    /usr/local/include/boost/numeric/ublas/matrix.hpp:5977:18: error: ‘make_array’ is not a member of ‘boost::serialization’
                 ar & serialization::make_array(data_, N);
                      ^~~~~~~~~~~~~
    FAILED: /usr/bin/c++   -I../../include -Igenerated -I/usr/local/include -I../../third-party/pbcopper/include -std=c++11 -Wall -Wextra -Wno-unused-parameter -Wno-unused-variable -Wno-unused-local-typedefs -O2 -g -DNDEBUG   -fPIC -MD -MT src/CMakeFiles/cc2.dir/align/PairwiseAlignment.cpp.o -MF src/CMakeFiles/cc2.dir/align/PairwiseAlignment.cpp.o.d -o src/CMakeFiles/cc2.dir/align/PairwiseAlignment.cpp.o -c ../../src/align/PairwiseAlignment.cpp
    In file included from /usr/local/include/boost/numeric/ublas/vector.hpp:21:0,
                     from /usr/local/include/boost/numeric/ublas/matrix.hpp:18,
                     from ../../src/align/PairwiseAlignment.cpp:42:
    /usr/local/include/boost/numeric/ublas/storage.hpp: In member function ‘void boost::numeric::ublas::unbounded_array<T, ALLOC>::serialize(Archive&, unsigned int)’:
    /usr/local/include/boost/numeric/ublas/storage.hpp:299:18: error: ‘make_array’ is not a member of ‘boost::serialization’
                 ar & serialization::make_array(data_, s);
                      ^~~~~~~~~~~~~
    /usr/local/include/boost/numeric/ublas/storage.hpp: In member function ‘void boost::numeric::ublas::bounded_array<T, N, ALLOC>::serialize(Archive&, unsigned int)’:
    /usr/local/include/boost/numeric/ublas/storage.hpp:494:18: error: ‘make_array’ is not a member of ‘boost::serialization’
                 ar & serialization::make_array(data_, s);
                      ^~~~~~~~~~~~~
    In file included from ../../src/align/PairwiseAlignment.cpp:42:0:
    /usr/local/include/boost/numeric/ublas/matrix.hpp: In member function ‘void boost::numeric::ublas::c_matrix<T, M, N>::serialize(Archive&, unsigned int)’:
    /usr/local/include/boost/numeric/ublas/matrix.hpp:5977:18: error: ‘make_array’ is not a member of ‘boost::serialization’
                 ar & serialization::make_array(data_, N);
                      ^~~~~~~~~~~~~
    ../../third-party/pbcopper/src/logging/Logging.cpp: In destructor ‘PacBio::Logging::Logger::Logger()’:
    ../../third-party/pbcopper/src/logging/Logging.cpp:111:64: warning: throw will always call terminate() [-Wterminate]
             throw std::runtime_error("this logger is already dead!");
                                                                    ^
    ../../third-party/pbcopper/src/logging/Logging.cpp:111:64: note: in C++11 destructors default to noexcept
    ninja: build stopped: subcommand failed.
    Configuring with command `cmake -GNinja -DUNY_build_bin=0 -DPYTHON_SWIG=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DPYTHON_EXECUTABLE=/usr/bin/python -DUNY_build_tests=0 /tmp/pip-ov_qGE-build`
    -- The CXX compiler identification is GNU 6.4.0
    -- The C compiler identification is GNU 6.4.0
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Boost version: 1.64.0
    -- Performing Test HAS_NO_UNUSED_LOCAL_TYPEDEFS
    -- Performing Test HAS_NO_UNUSED_LOCAL_TYPEDEFS - Success
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /tmp/pip-ov_qGE-build/build/temp.linux-x86_64-2.7
    Building with command `/usr/bin/ninja _ConsensusCore2`
    [1/61] Building CXX object external/pbcopper/build/src/CMakeFiles/pbcopper.dir/cli/CLI.cpp.o
    [2/61] Building CXX object external/pbcopper/build/src/CMakeFiles/pbcopper.dir/cli/HelpPrinter.cpp.o
    [3/61] Building CXX object external/pbcopper/build/src/CMakeFiles/pbcopper.dir/cli/Interface.cpp.o
    [4/61] Building CXX object external/pbcopper/build/src/CMakeFiles/pbcopper.dir/cli/Option.cpp.o
    [5/61] Building CXX object external/pbcopper/build/src/CMakeFiles/pbcopper.dir/cli/Parser.cpp.o
    [6/61] Building CXX object external/pbcopper/build/src/CMakeFiles/pbcopper.dir/cli/Results.cpp.o
    [7/61] Building CXX object external/pbcopper/build/src/CMakeFiles/pbcopper.dir/cli/toolcontract/ResolvedToolContract.cpp.o
    [8/61] Building CXX object external/pbcopper/build/src/CMakeFiles/pbcopper.dir/cli/VersionPrinter.cpp.o
    [9/61] Building CXX object external/pbcopper/build/src/CMakeFiles/pbcopper.dir/data/Cigar.cpp.o
    [10/61] Building CXX object external/pbcopper/build/src/CMakeFiles/pbcopper.dir/cli/toolcontract/JsonPrinter.cpp.o
    [11/61] Building CXX object external/pbcopper/build/src/CMakeFiles/pbcopper.dir/data/CigarOperation.cpp.o
    [12/61] Building CXX object external/pbcopper/build/src/CMakeFiles/pbcopper.dir/data/MovieName.cpp.o
    [13/61] Building CXX object external/pbcopper/build/src/CMakeFiles/pbcopper.dir/data/RSMovieName.cpp.o
    [14/61] Building CXX object external/pbcopper/build/src/CMakeFiles/pbcopper.dir/logging/Logging.cpp.o
    [15/61] Building CXX object external/pbcopper/build/src/CMakeFiles/pbcopper.dir/utility/CallbackTimer.cpp.o
    [16/61] Building CXX object src/CMakeFiles/cc2.dir/align/AffineAlignment.cpp.o
    [17/61] Building CXX object src/CMakeFiles/cc2.dir/align/AlignConfig.cpp.o
    [18/61] Building CXX object src/CMakeFiles/cc2.dir/align/BandedChainAlignment.cpp.o
    [19/61] Building CXX object src/CMakeFiles/cc2.dir/align/LinearAlignment.cpp.o
    [20/61] Building CXX object src/CMakeFiles/cc2.dir/align/PairwiseAlignment.cpp.o
    [21/61] Building CXX object src/CMakeFiles/cc2.dir/matrix/BasicDenseMatrix.cpp.o
    [22/61] Building CXX object src/CMakeFiles/cc2.dir/matrix/ScaledMatrix.cpp.o
    [23/61] Building CXX object src/CMakeFiles/cc2.dir/matrix/SparseMatrix.cpp.o
    [24/61] Building CXX object src/CMakeFiles/cc2.dir/models/MarginalModelForm.cpp.o
    [25/61] Building CXX object src/CMakeFiles/cc2.dir/models/P6C4NoCovModel.cpp.o
    [26/61] Building CXX object src/CMakeFiles/cc2.dir/models/PwSnrAModelForm.cpp.o
    [27/61] Building CXX object src/CMakeFiles/cc2.dir/models/PwSnrModelForm.cpp.o
    [28/61] Building CXX object src/CMakeFiles/cc2.dir/models/S_P1C1Beta_Model.cpp.o
    [29/61] Building CXX object src/CMakeFiles/cc2.dir/models/S_P1C1v1_Model.cpp.o
    [30/61] Building CXX object src/CMakeFiles/cc2.dir/models/S_P1C1v2_Model.cpp.o
    [31/61] Building CXX object src/CMakeFiles/cc2.dir/models/S_P2C2v5_Model.cpp.o
    [32/61] Building CXX object src/CMakeFiles/cc2.dir/models/SnrModelForm.cpp.o
    [33/61] Building CXX object src/CMakeFiles/cc2.dir/poa/PoaAlignmentMatrix.cpp.o
    [34/61] Building CXX object src/CMakeFiles/cc2.dir/poa/PoaConsensus.cpp.o
    [35/61] Building CXX object src/CMakeFiles/cc2.dir/poa/PoaGraph.cpp.o
    [36/61] Building CXX object src/CMakeFiles/cc2.dir/poa/PoaGraphImpl.cpp.o
    [37/61] Building CXX object src/CMakeFiles/cc2.dir/poa/PoaGraphTraversals.cpp.o
    [38/61] Building CXX object src/CMakeFiles/cc2.dir/poa/RangeFinder.cpp.o
    [39/61] Building CXX object src/CMakeFiles/cc2.dir/AbstractIntegrator.cpp.o
    [40/61] Building CXX object src/CMakeFiles/cc2.dir/Coverage.cpp.o
    [41/61] Building CXX object src/CMakeFiles/cc2.dir/EasyReadScorer.cpp.o
    FAILED: /usr/bin/c++   -I../../include -Igenerated -I/usr/local/include -I../../third-party/pbcopper/include -std=c++11 -Wall -Wextra -Wno-unused-parameter -Wno-unused-variable -Wno-unused-local-typedefs -O2 -g -DNDEBUG   -fPIC -MD -MT src/CMakeFiles/cc2.dir/align/AffineAlignment.cpp.o -MF src/CMakeFiles/cc2.dir/align/AffineAlignment.cpp.o.d -o src/CMakeFiles/cc2.dir/align/AffineAlignment.cpp.o -c ../../src/align/AffineAlignment.cpp
    In file included from /usr/local/include/boost/numeric/ublas/vector.hpp:21:0,
                     from /usr/local/include/boost/numeric/ublas/matrix.hpp:18,
                     from ../../src/align/AffineAlignment.cpp:44:
    /usr/local/include/boost/numeric/ublas/storage.hpp: In member function ‘void boost::numeric::ublas::unbounded_array<T, ALLOC>::serialize(Archive&, unsigned int)’:
    /usr/local/include/boost/numeric/ublas/storage.hpp:299:18: error: ‘make_array’ is not a member of ‘boost::serialization’
                 ar & serialization::make_array(data_, s);
                      ^~~~~~~~~~~~~
    /usr/local/include/boost/numeric/ublas/storage.hpp: In member function ‘void boost::numeric::ublas::bounded_array<T, N, ALLOC>::serialize(Archive&, unsigned int)’:
    /usr/local/include/boost/numeric/ublas/storage.hpp:494:18: error: ‘make_array’ is not a member of ‘boost::serialization’
                 ar & serialization::make_array(data_, s);
                      ^~~~~~~~~~~~~
    In file included from ../../src/align/AffineAlignment.cpp:44:0:
    /usr/local/include/boost/numeric/ublas/matrix.hpp: In member function ‘void boost::numeric::ublas::c_matrix<T, M, N>::serialize(Archive&, unsigned int)’:
    /usr/local/include/boost/numeric/ublas/matrix.hpp:5977:18: error: ‘make_array’ is not a member of ‘boost::serialization’
                 ar & serialization::make_array(data_, N);
                      ^~~~~~~~~~~~~
    FAILED: /usr/bin/c++   -I../../include -Igenerated -I/usr/local/include -I../../third-party/pbcopper/include -std=c++11 -Wall -Wextra -Wno-unused-parameter -Wno-unused-variable -Wno-unused-local-typedefs -O2 -g -DNDEBUG   -fPIC -MD -MT src/CMakeFiles/cc2.dir/align/PairwiseAlignment.cpp.o -MF src/CMakeFiles/cc2.dir/align/PairwiseAlignment.cpp.o.d -o src/CMakeFiles/cc2.dir/align/PairwiseAlignment.cpp.o -c ../../src/align/PairwiseAlignment.cpp
    In file included from /usr/local/include/boost/numeric/ublas/vector.hpp:21:0,
                     from /usr/local/include/boost/numeric/ublas/matrix.hpp:18,
                     from ../../src/align/PairwiseAlignment.cpp:42:
    /usr/local/include/boost/numeric/ublas/storage.hpp: In member function ‘void boost::numeric::ublas::unbounded_array<T, ALLOC>::serialize(Archive&, unsigned int)’:
    /usr/local/include/boost/numeric/ublas/storage.hpp:299:18: error: ‘make_array’ is not a member of ‘boost::serialization’
                 ar & serialization::make_array(data_, s);
                      ^~~~~~~~~~~~~
    /usr/local/include/boost/numeric/ublas/storage.hpp: In member function ‘void boost::numeric::ublas::bounded_array<T, N, ALLOC>::serialize(Archive&, unsigned int)’:
    /usr/local/include/boost/numeric/ublas/storage.hpp:494:18: error: ‘make_array’ is not a member of ‘boost::serialization’
                 ar & serialization::make_array(data_, s);
                      ^~~~~~~~~~~~~
    In file included from ../../src/align/PairwiseAlignment.cpp:42:0:
    /usr/local/include/boost/numeric/ublas/matrix.hpp: In member function ‘void boost::numeric::ublas::c_matrix<T, M, N>::serialize(Archive&, unsigned int)’:
    /usr/local/include/boost/numeric/ublas/matrix.hpp:5977:18: error: ‘make_array’ is not a member of ‘boost::serialization’
                 ar & serialization::make_array(data_, N);
                      ^~~~~~~~~~~~~
    FAILED: /usr/bin/c++   -I../../include -Igenerated -I/usr/local/include -I../../third-party/pbcopper/include -std=c++11 -Wall -Wextra -Wno-unused-parameter -Wno-unused-variable -Wno-unused-local-typedefs -O2 -g -DNDEBUG   -fPIC -MD -MT src/CMakeFiles/cc2.dir/align/LinearAlignment.cpp.o -MF src/CMakeFiles/cc2.dir/align/LinearAlignment.cpp.o.d -o src/CMakeFiles/cc2.dir/align/LinearAlignment.cpp.o -c ../../src/align/LinearAlignment.cpp
    In file included from /usr/local/include/boost/numeric/ublas/vector.hpp:21:0,
                     from /usr/local/include/boost/numeric/ublas/matrix.hpp:18,
                     from ../../src/align/LinearAlignment.cpp:57:
    /usr/local/include/boost/numeric/ublas/storage.hpp: In member function ‘void boost::numeric::ublas::unbounded_array<T, ALLOC>::serialize(Archive&, unsigned int)’:
    /usr/local/include/boost/numeric/ublas/storage.hpp:299:18: error: ‘make_array’ is not a member of ‘boost::serialization’
                 ar & serialization::make_array(data_, s);
                      ^~~~~~~~~~~~~
    /usr/local/include/boost/numeric/ublas/storage.hpp: In member function ‘void boost::numeric::ublas::bounded_array<T, N, ALLOC>::serialize(Archive&, unsigned int)’:
    /usr/local/include/boost/numeric/ublas/storage.hpp:494:18: error: ‘make_array’ is not a member of ‘boost::serialization’
                 ar & serialization::make_array(data_, s);
                      ^~~~~~~~~~~~~
    In file included from ../../src/align/LinearAlignment.cpp:57:0:
    /usr/local/include/boost/numeric/ublas/matrix.hpp: In member function ‘void boost::numeric::ublas::c_matrix<T, M, N>::serialize(Archive&, unsigned int)’:
    /usr/local/include/boost/numeric/ublas/matrix.hpp:5977:18: error: ‘make_array’ is not a member of ‘boost::serialization’
                 ar & serialization::make_array(data_, N);
                      ^~~~~~~~~~~~~
    ../../third-party/pbcopper/src/logging/Logging.cpp: In destructor ‘PacBio::Logging::Logger::~Logger()’:
    ../../third-party/pbcopper/src/logging/Logging.cpp:111:64: warning: throw will always call terminate() [-Wterminate]
             throw std::runtime_error("this logger is already dead!");
                                                                    ^
    ../../third-party/pbcopper/src/logging/Logging.cpp:111:64: note: in C++11 destructors default to noexcept
    ninja: build stopped: subcommand failed.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-ov_qGE-build/setup.py", line 172, in <module>
        cmdclass={"build_ext": MyBuildExt}
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "build/bdist.linux-x86_64/egg/setuptools/command/install.py", line 61, in run
      File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run
        self.run_command('build')
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
        self.run_command(cmd_name)
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/distutils/command/build_ext.py", line 337, in run
        self.build_extensions()
      File "/usr/lib/python2.7/distutils/command/build_ext.py", line 446, in build_extensions
        self.build_extension(ext)
      File "/tmp/pip-ov_qGE-build/setup.py", line 155, in build_extension
        cmake(thisDir, self.build_temp, targets)
      File "/tmp/pip-ov_qGE-build/setup.py", line 120, in __call__
        raise RuntimeError("failed to build the project")
    RuntimeError: failed to build the project
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-ov_qGE-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-4a2S6s-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-ov_qGE-build/
```

**Comment by mhsieh** [comment]
This doesn't look like a pitchfork build, I will find Armin to look at this.

**Comment by mhsieh** [comment]
feel free to move the issue to unanimity, I will let this open till it's solved

**Comment by SoapZA** [comment]
@gabyrech Thanks for using our software. This issue is a boost issue that has also cropped up in Conda: https://svn.boost.org/trac10/ticket/12516
The best approach would be to patch your local Boost installation.

**Comment by gabyrech** [comment]
Hi! @SoapZA !, what you mean to patch the local Boost installation? Are you referring to some specific patch?
Thanks!

**Comment by SoapZA** [comment]
@gabyrech Try pulling the commit https://github.com/boostorg/serialization/commit/1d86261581230e2dc5d617a9b16287d326f3e229
as patch (on Github, you can append `.patch` to all commit URLs, so download https://github.com/boostorg/serialization/commit/1d86261581230e2dc5d617a9b16287d326f3e229.patch) and apply it to your boost installation.

Unfortunately, boost 1.64 is broken in this regard (boost is a bit of a slow-moving bureaucratic monster). You can also try the 1.65 beta if you dare touch `bjam`.
